### ISSUE TITLE
Going in minus

### ISSUE THREAD

**Issue by Arpit8081** [mopsicus/infinite-scroll-unity#10]
Hi, In your script is going forward like (0,1,2....). But I want to go both direction backward also. like (0,-1,-2,...). Where can add this thing in InfineScroll.cs. Thank you

**Comment by mopsicus** [comment]
Hi, 
I don't know how to do it, right now, need some research
you can try do it by yourself, all sources are available

**Comment by Arpit8081** [comment]
Hi, How did you find infiniteScroll script?

**Comment by mopsicus** [comment]
I wrote it by myself) what you mean?
