### ISSUE TITLE
Flicker problem

### ISSUE THREAD

**Issue by agrobost** [mopsicus/infinite-scroll-unity#11]
There is a flicker problem when using a canvas with 
Scale with screen Size: x:1536/y:2730 
Match: 1
Ref Pixel Per Unit: 100

Do you have a solution to remedy this problem?
Thank's !

**Comment by mopsicus** [comment]
Are you sure that is a script problem? Maybe your items are too "heavy"? 
Did you test it with empty item prefabs? Or maybe you can make a screen video?

**Comment by agrobost** [comment]
I just modify the canvas component in the demo scenes to match with this config

> Scale with screen Size: x:1536/y:2730
> Match: 1
> Ref Pixel Per Unit: 100

And the problem occurs :/

**Comment by mopsicus** [comment]
Ok, I will check it

**Comment by mopsicus** [comment]
On which device did you test it? PC, Android, iOS?

**Comment by agrobost** [comment]
I test on android.

**Comment by agrobost** [comment]
Hello, did you find a solution?
Best regards

**Comment by AndrewKo-MA** [comment]
flickering happens if you scroll between 0-1 element or last 2 elements while scroll velocity > 0, actually you don't see it in game mode, but in scene view its noticeably, from me it causes to intensive data rebinding due to `Scroll.OnFill`
