### ISSUE TITLE
If you scroll to hard for some time scroll is empty

### ISSUE THREAD

**Issue by AndrewKo-MA** [mopsicus/infinite-scroll-unity#14]
I believe it's because Update call happens one time per frame and changes position only for +-1 and may happen situation when you wait about 30-40 frames before scroll complete updated items

**Comment by mopsicus** [comment]
Yeah, there is that scroll effect. You can tune behavior by changing scrollrect options:
![Screenshot at Feb 06 10-12-41](https://user-images.githubusercontent.com/17999592/73913987-55015b00-48c9-11ea-9b4a-f91bbc6c82f4.png)
or in code
