### ISSUE TITLE
Support for multiple cells

### ISSUE THREAD

**Issue by robpot95** [mopsicus/infinite-scroll-unity#16]
Any plans for support multiple cells. Since would be nice to have more than one item next to eachother

**Comment by mopsicus** [comment]
What do you mean?

**Comment by robpot95** [comment]
Like a grid layout

**Comment by mopsicus** [comment]
I don't think to do some special mode for that, you can make item container with any data and view

**Comment by robpot95** [comment]
Well, when i add a grid layout to the content. Items are appearing weird

**Comment by mopsicus** [comment]
Anyway, I'll support current realization as known as default data driven solution. If you want to add some features – do it :)
