### ISSUE TITLE
When cell count equal to 1, it will occur error while dragging scroll view

### ISSUE THREAD

**Issue by jasontung** [mopsicus/infinite-scroll-unity#17]
![截圖 2020-07-21 下午3 28 07](https://user-images.githubusercontent.com/32433643/88025400-cfb3ef00-cb66-11ea-8eb1-7998c77ce37d.png)

**Comment by mopsicus** [comment]
Oh, I'll check it

**Comment by mopsicus** [comment]
Fixed
