### ISSUE TITLE
How to autoscroll to target?

### ISSUE THREAD

**Issue by theolovesyou** [mopsicus/infinite-scroll-unity#18]
I use MoveToSide method to scroll to end position and if target is found i stopped scrolling.
but items spawned after scrolling. 
i changed the SCROLL_SPEED, SCROLL_DURATION
but it did not work.

i mean OnFill is called at first few times,
and is not called even if scroll is moving.

is there a good way to autoscroll to target? 
thanks!

**Comment by EricBatlle** [comment]
I've tried the following:

```
public void MoveTo(float position)
{
	_scroll.verticalNormalizedPosition = position/ _count;
}
```

being position the target index in the list, but it won't work, it scrolls correctly, but the list looks empty, you had to manually scroll (doesn't matter the direction) to update the items inside the list, any idea?
