### ISSUE TITLE
How to reset items in list ? 

### ISSUE THREAD

**Issue by xabio** [mopsicus/infinite-scroll-unity#19]
When i launch `Scroll.InitData(0);` to reset the list, i get some errors, How can I reste the list content? Thank you

**Comment by mopsicus** [comment]
Don't init scroll-list if your data is empty. Anyway, you can refresh data with UpdateVisible method, or RefreshViews when you need to update views objects.

**Comment by xabio** [comment]
Hi Igor, thank you for the reply.
So, which commands I should send to update the list , event if the list has
an empty List as data
For example:
FriendList= new List<Item>();
Scroll.InitData(FriendsList.Count); //this will throw an exception

Scroll.UpdateVisible() will be enough?

**Comment by mopsicus** [comment]
You have to init list when data is not empty:
if (FriendsList.Count >0) {
Scroll.InitData(FriendsList.Count);
}
If you update data in FriendsList, you can update it directly in a Scroll -> Scroll.UpdateVisible(), or just scroll the list.
Anyway, do not init Scroll if data for show is empty.

**Comment by xabio** [comment]
But how I clean the list of items? Is there a method for that.
Many thanks you are the boss

**Comment by mopsicus** [comment]
You can call Scroll.Recycle or Scroll.RecycleAll

**Comment by xabio** [comment]
That only hides the views ...is not the best way right?
