### ISSUE TITLE
Update lag on high velocity

### ISSUE THREAD

**Issue by CheeryLee** [mopsicus/infinite-scroll-unity#24]
Accordingly to my comment in https://github.com/mopsicus/infinite-scroll-unity/issues/23

If we want to change scrollbar (exactly the bar, not by dragging scroll view) position too fast, there would be unpredictable behaviour: the component won't update views' positions. They will stuck outside content transform bounds. Nextly, if we would drag scroll view, but with much less velocity, views will change their positions little by little.

Currently I don't know how to beat this issue due to lack of the documentation and comments about how UpdateVertical and UpdateHorizontal methods work.

@mopsicus what do you think about it?

**Comment by mopsicus** [comment]
There is some bug, yeah. But now I really have no time to do smth with that. 
If you can suggest some good solution – I will merge it
