### ISSUE TITLE
The dictionary key exception when initialize only 1 element still happening

### ISSUE THREAD

**Issue by PhuocNG0308** [mopsicus/infinite-scroll-unity#34]
I'm using v2.0.1. 

It might not happen when just started Play Mode. After pull it (from Top/Down side), it will be throw this exception
![image](https://github.com/user-attachments/assets/d0f035aa-5c38-4598-84f0-d830cc4f6ec6)

**Comment by mopsicus** [comment]
Hi, how to reproduce it?

**Comment by PhuocNG0308** [comment]
I'm using Demo2 in v2.0.1

Reproducing:
- Go to Demo2, change Demo 2 behaviour attached in **_Scripts_** Object
- Set **_Count_** from 100 to 1
- Go to Play Mode
- Drag scroll view to Pull Mode from Top or Down

**Comment by mopsicus** [comment]
Yes, I've tried it before, but I couldn't reproduce this error.

**Comment by PhuocNG0308** [comment]
Any different from Android Platform, I'm playing in Android. And just checked, I'm using v2.0.1

**Comment by mopsicus** [comment]
Are you do it in editor? Or on device?

**Comment by PhuocNG0308** [comment]
in Editor 2022.3.40f1

**Comment by mopsicus** [comment]
I'll check it out, but I think it's just editor behavior. Try it on device
