### ISSUE TITLE
Why there's an InitData call in UpdateVertical method ?

### ISSUE THREAD

**Issue by wangyongcong** [mopsicus/infinite-scroll-unity#36]
I'm adding "snap to item" feature to scroller. While reading the code, I encountered some issues and would like to ask for your help.

In the ```UpdateVertical``` and ```UpdateHorizontal``` method, there's a condition check which could trigger a call to ```InitData```

https://github.com/mopsicus/uis/blob/4e608e3e8e5f85bf05f6c805e58e39a70c85db3e/Runtime/Scroller.cs#L463

I can't figure out what's the purpose of this ```if``` condition.  I'd appreciate it if you could explain it to me. Thank you.

**Comment by mopsicus** [comment]
To be honest, now I don't remember why I added this condition..... Probably, in some cases, when scrolling occurs at high speed and there may be negative values - the list was not updated and redrawn.

**Comment by wangyongcong** [comment]
Thank you for your reponse. I will write some test to see what could hanppen.
