### ISSUE TITLE
Not display numbers

### ISSUE THREAD

**Issue by Arpit8081** [mopsicus/infinite-scroll-unity#9]
Hi, I try your code in my already created Canvas but I can not see any number on that one. I can see number in Hierarchy but not in Game display. Please find screen-sort of the error. thank you.
![error](https://user-images.githubusercontent.com/33547113/62537357-1cb08f80-b848-11e9-8834-09b7e8d1cf1f.png)

**Comment by mopsicus** [comment]
Hi, I can't help you by looking on screenshot)
Give me some code where you implement list and fill items

**Comment by Arpit8081** [comment]
Hi, thank you for your msg. 
How can I send you my some of the code to you?

**Comment by Arpit8081** [comment]
I am using same code of your. I have different code for different assets. I did same thing like you did in your project but I can not see any number.
